### PR TITLE
Match binary body

### PR DESCRIPTION
**Pull request by torrefatto**
Hi! As discussed [here](https://github.com/lipanski/mockito/issues/95), this PR introduces the possibility to create a mock that matches the exact bytes of a **binary** payload.
We managed not to change the existing API, introducing a new `Matcher` variant: `Matcher::Binary(BinaryBody)`.
There are now three ways to instantiate a mock that matches with this new `Matcher`:

  1. passing a **mutable** reference to a `File` (open in read mode)
   ```rust
   let mut file = std::fs::File::open("path/to/file")?;
   let _m = mock("POST", "/").with_body(&mut file).create();
   ```
  2. passing a `Path` (**this panics** in case of failure to read the file content from the path)
  ```rust
  let path = std::path::Path::new("path/to/file");
  let _m = mock("POST", "/").with_body(path).create();
  ```
  3. directly passing a binary payload (i.e. a `Vec<u8>`)
  ```rust
   let content: Vec<u8> = vec![01, 02, 03, 04];
   let _m = mock("POST", "/").with_body(content).create();
  ```
All these three ways have the associated functions implemented by `BinaryBody`.

### CODE REVIEW

**Comment by lipanski** [comment]
@torrefatto thanks a lot for the PR! on first sight it looks good and in the style of the library.

for whatever reason the Travis integration didn't work but the build is red: https://travis-ci.org/github/lipanski/mockito - can you fix those linting issues and get Travis back to green please? there are instructions [inside the README](https://github.com/lipanski/mockito/#code-style) about how to run the linter. note that it runs on a particular Rust version (though sometimes latest stable produces the same results).

**Comment by torrefatto** [comment]
Hi @lipanski, I prepared two PR to fix the linting issues: #129 and #130. Choose between one and then I can rebase this PR onto the new master.

**Comment by lipanski** [comment]
@torrefatto so I merged the second one => please rebase :rocket:

**Comment by torrefatto** [comment]
Mmm, apparently I didn't do my homework properly. I had to run clippy with `cargo clippy --lib --tests --all-features -- -D clippy::pedantic -D clippy::nursery`. The linting step fails :sweat_smile:. Lemme fix it.

**Comment by torrefatto** [comment]
Ok, this is annoying. It [seems](https://travis-ci.com/github/lipanski/mockito/jobs/405076294) that the `1.36.0` stable toolchain is not compatible with the clippy options I pasted above (that caused the CI to fail in the previous attempt).
I don't know how to proceed.

**Comment by lipanski** [comment]
@torrefatto that was probably not obvious from the README, but clippy should always be run using the min. support Rust version (1.36.0), in order to preserve backwards compatibility. I fixed that in https://github.com/lipanski/mockito/commit/7317881649ab7f73a5b58f4ad00436687cd7ce7f and updated the README to make it more clear.

your feature is now on master - please give it a try. if there are no issues, I'll make a proper release later next week.

thanks for your contribution :balloon:

**Comment by torrefatto** [comment]
Hi @lipanski! Sorry for the very late reply. Today we'll test it. I'll get back soon.

**Comment by torrefatto** [comment]
Thumbs up. It worked :rocket: 

Thank you for all the time and effort :+1:

**Comment by lipanski** [comment]
Released in [0.28.0](https://github.com/lipanski/mockito/releases/tag/0.28.0).

**Pull request merged**
