### PR TITLE
Adds delayed mocks

### LINKED ISSUE #31: is it possible to add latency mocking?
Thanks for the very useful crate.

For testing purposes, I need to mock a server that will return a 200 response after, say, 400ms!
Is it currently possible to do it?

### PR DESCRIPTION
**Pull request by sr-gi**
Adds optional delays to mocks

Fixes #31 #64 #160

### CODE REVIEW

**Comment by sr-gi** [comment]
@lipanski how would you feel about something like this? I think the change is pretty minimal.

I've locally tested it against https://github.com/lipanski/mockito/issues/160#issuecomment-1451841112 and it's being consistent with he delays.

**Comment by lipanski** [comment]
@sr-gi this feature is a bit too specific for this crate. instead, is there a way to make the `with_body_from_request` block accept futures? seems like using `tokio::time::sleep` is the way to go.

**Comment by sr-gi** [comment]
I'd argue this is actually something pretty useful for an http mock crate. This lets you simulate network delays for instance, which are pretty common and something you may want your code (as in the one using the mock) to account for.

**Comment by lipanski** [comment]
I don't challenge the use case, but there's already a solution for that (`with_body_from_request`) which needs some tuning. I'd like to keep the public interface of this crate fairly minimal, whenever possible.

**Comment by sr-gi** [comment]
I'm not fluent enough with futures to make then change then, sorry.

**Pull request closed without merging**
