### PR TITLE
Change usage of rustc_serialize to serde

### PR DESCRIPTION
**Pull request by mikeastock**
I'm interested in adding support for users to match mocks based on the request body. This PR makes that a little bit easier. Are you interested in that feature?

### CODE REVIEW

**Comment by lipanski** [comment]
thanks for your effort. I'll have a look during the weekend.

**Comment by mikeastock** [comment]
I believe this should pass now

**Comment by lipanski** [comment]
@mikeastock looks good. can you please squash your commits?

**Comment by mikeastock** [comment]
Done

**Pull request merged**
