### PR TITLE
Make clippy happy

### PR DESCRIPTION
**Pull request by macisamuele**
The goal of this PR is to make this repository work well with [clippy](https://github.com/rust-lang/rust-clippy).
Clippy provides guidelines on how to write more idiomatic rust code and allow to reduce complexity.
I did noticed those issues while running `cargo clippy` on a personal library as clippy runs on all the dependencies (and mockito is among them 😃 ).

The provided changes are directly suggested by clippy and I did no other fixes that could seem reasonable (for example the not needed write call in [here](https://github.com/lipanski/mockito/compare/master...macisamuele:maci-run-clippy?expand=1#diff-2873e3b87f87572c686867a1c112e3fdR114)).

In order to guarantee that the codebase will be compliant with clippy I've added the checks on the travis files, so the build won't be green if clippy is unhappy.

NOTE: I would also suggest to use [`cargo fmt`](https://github.com/rust-lang/rustfmt) to ensure that the stile of the codebase is consistent, but this will result into a much bigger change and is not blocking me in any way. So I would prefer the maintainer decides whether to do it or not (TIP: on my personal project I've set up [pre-commit](https://pre-commit.com) to ensure style consistency, [example](https://github.com/macisamuele/jsonschema-validator/blob/master/.pre-commit-config.yaml#L17)).

### CODE REVIEW

**Comment by lipanski** [comment]
thanks for your contribution. can you please also extend the *Development* section of the `README` with information about how to install & run clippy (ideally after the `Run tests` part)?

**Comment by macisamuele** [comment]
Sure thing, before writing it wanted to run the idea first :)

**Comment by lipanski** [comment]
@macisamuele but just clippy for now, `cargo fmt` is a different story :)

**Comment by lipanski** [comment]
thanks again! :1st_place_medal:

**Pull request merged**
