### PR TITLE
Proposal: multiple mock matching

### PR DESCRIPTION
**Pull request by xneomac**
This is an implementation proposal of the feature previously discussed in issue #97.

The idea is to detect if there is multiple mock matching the same request and calling them while the number of request expected is not reached. When it is reached we call the next one. If there is no more available we keep calling the last one.

### CODE REVIEW

**Comment by lipanski** [comment]
@xneomac can you please rebase this branch? I merged your other PR into master and fixed both Travis and Appveyor.

**Comment by Jonathas-Conceicao** [comment]
Any updates on this?

I think this is a nice feature to have, certainly makes mocks more flexible to design. I would like to see this merged.

I have [forked and rebased](https://github.com/OSSystems/mockito/tree/topic/multiple_mock_matching) the commit from @xneomac so I could use for my tests in the mean time (could't build the original fork as is). And it seams to work as intended.

**Comment by lipanski** [comment]
@Jonathas-Conceicao released with [0.25.0](https://github.com/lipanski/mockito/releases/tag/0.25.0). Thanks for your effort and thanks to @xneomac for building the feature :1st_place_medal:

**Comment by lipanski** [comment]
Fixed a small bug with https://github.com/lipanski/mockito/commit/96f3e302b76a01579fd5026c82b5d1df7d9dc087 and released in [0.25.1](https://github.com/lipanski/mockito/releases/tag/0.25.1)

**Pull request merged**
