### PR TITLE
Change example for use mockito in docs

### PR DESCRIPTION
**Pull request by mikeastock**

### CODE REVIEW

**Comment by lipanski** [comment]
@mikeastock well technically speaking `mockito::SERVER_URL` is *the only thing* you need there, even if you might want the whole `mockito` in your test module. am I missing something?

**Comment by mikeastock** [comment]
This change was to make the example in the docs work out of the box.

```rust
#[cfg(test)]
use mockito::SERVER_URL;

#[cfg(not(test))]
const URL: &'static str = "https://api.twitter.com";

#[cfg(test)]
const URL: &'static str = mockito::SERVER_URL;
``` 

The above doesn't work as the `SERVER_URL` is explicitly imported but used below via the module.

**Comment by mikeastock** [comment]
I can change the reference to `SERVER_URL` to just not use the module if you would like!

**Comment by lipanski** [comment]
got it now. no, I'm fine with your approach. thx :palm_tree: :camel:

**Pull request merged**
