### PR TITLE
Allow generating response programmatically

### LINKED ISSUE #64: Mock with latency?
I'm mocking an API that returns a json with content saying if a previous query is running or completed. So I have to poll that API until the initial query is complete. For example:
* From 0 to X ms, `GET` on `/status` should return `{"status": "starting"}`
* From X to Y ms, `GET` on `/status` should return `{"status": "running"}`
* From Y ms and updward, `GET` on `/status` should return `{"status": "complete"}`

I want to test my exponential backoff until completion.

I'm not sure how to do this with mockito right now. Since all requests will be on the same route with the same information (only the return data will be different) I cannot create them all beforehand; how would mockito known which mock to use if they are all identical?

Issue #31 asked for something similar and a suggestion was to use threads to create the mocks. An `Arc<Barrier>>` can easily be used to synchronize threads (instead of a loop as suggested in #31).

I tried spawning a thread to create and destroy the mocks with the different behavior at the proper timing but got a deadlock. The lock happens at https://github.com/lipanski/mockito/blob/459049a780c49e8837c77cba047b76d5606b322e/src/lib.rs#L774

I also tried to put my client performing the `GET` in its thread instead and creating the mocks in the "main" test thread but this does not work since reqwest/tokio is not `Send`.

For now I'm kind of stucked... Any suggestion? Thanks!

### PR DESCRIPTION
**Pull request by kornelski**
Fixes #64

### CODE REVIEW

**Comment by lipanski** [comment]
first of all, thanks for this PR :1st_place_medal: 

a few notes:

1. please check the 1.32 failures in Travis. I'm not against bumping up the minimum supported version but only if there are no (easy) fixes.

2. what happens if we'd like to change the response status programmatically? or the headers? is there any way this could be adressed here? if not, I'm actually fine with your implementation but the interface might change once we bring the status & headers in.

3. I assume you've used the chunked transfer-encoding because you don't have access to the body at all so it's hard to compute the content length? or could we still have an option for the content-length based transfer?

**Comment by kornelski** [comment]
1. fixed
2. the callback is called too late to change these. It's better to have a separate API for this.
3. Chunked encoding allows the callback to stream the response without buffering. It makes it possible to output some data, flush/wait, then output more.

**Comment by lipanski** [comment]
@kornelski 

1. you've hit the clippy failures now (which is set to 1.32 as well). clippy can be changed to stable if you want but that brings other joys (=errors to fix).

2. ok, fair enough.

3. ok, thanks for the explanation.

**Comment by kornelski** [comment]
Updated

**Comment by lipanski** [comment]
Released as 0.19.0 :rocket: Thanks!

**Pull request merged**
