### PR TITLE
Update to hyper 1

### LINKED ISSUE #188: Migrating to hyper v1
Hello,

Now that hyper released a new major version, is mockito interested in migrating over?
See: https://hyper.rs/guides/1/upgrading/

### PR DESCRIPTION
**Pull request by tottoto**
Updates to `hyper` 1.

Resolves #188.

### CODE REVIEW

**Comment by lipanski** [comment]
Thank you :1st_place_medal:

**Comment by mstange** [comment]
I would be interested in a release with this fix.

**Comment by lipanski** [comment]
@mstange @tottoto Released as 1.5.0

**Comment by mstange** [comment]
Thank you!

**Pull request merged**
